name: Teste autom치tico de IA

on:
  push:
    branches:
      - main

jobs:
  exemplo:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar reposit칩rio
        uses: actions/checkout@v3
      - name: Exemplo de comando
        run: echo "Ol치, Jo칚o! O GitHub Actions est치 funcionando 游꿀"
